name: Pipeline 2

on:
  workflow_dispatch:
    inputs:
      DOCKER_TAG:
        description: "Docker tag for deployment"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying application..."

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

      - name: Configure Azure Credentials
        env:
          AZURE_SUBSCRIPTION_ID: bac12785-937a-4bd3-93d0-99f6eb81ba22
          AZURE_TENANT_ID: ed27b597-cea0-4942-8c6f-40e6a78bf47d
        run: |
          mkdir -p $HOME/.azure
          echo '[default]' > $HOME/.azure/credentials
          echo "azure_subscription_id = $AZURE_SUBSCRIPTION_ID" >> $HOME/.azure/credentials
          echo "azure_tenant_id = $AZURE_TENANT_ID" >> $HOME/.azure/credentials
          echo "azure_username = ${{ secrets.AZURE_USER_NAME }}" >> $HOME/.azure/credentials
          echo "azure_password = ${{ secrets.AZURE_PASSWORD }}" >> $HOME/.azure/credentials

      - name: Azure Login
        run: |
          az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
          az account set --subscription "bac12785-937a-4bd3-93d0-99f6eb81ba22"

      - name: Run Azure Commands
        run: |
          az account show
          az group list

      - name: Get Azure VM IP
        id: get-ip
        run: |
          VM_IP=$(az network public-ip show --name frontend-public-ip --resource-group myResourceGroup --query "ipAddress" -o tsv)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

      - name: Deploy to Azure VM
        env:
          DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}
          VM_IP: ${{ env.VM_IP }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Create deployment script
          cat > deploy.sh << 'EOL'
          #!/bin/bash

          # Docker login using credentials passed from GitHub Actions
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          # Pull and run the Docker image
          docker pull stalinrijal/aone-prep:$DOCKER_TAG
          docker run -d -p 3000:3000 stalinrijal/aone-prep:$DOCKER_TAG
          EOL

          # Copy deployment script to VM and execute
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deploy.sh adminuser@$VM_IP:~/deploy.sh
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa adminuser@$VM_IP "chmod +x ~/deploy.sh && sudo bash ~/deploy.sh"
